/v4l2_camera:
  ros__parameters:
    camera_frame_id: camera
    camera_info_url: "file:///home/your-path-here/src/v4l2_camera/boson:_flir_video.yaml"
    image_raw:
      compressed:
        format: png
        jpeg_quality: 95
        png_level: 3
        tiff:
          res_unit: inch
          xdpi: -1
          ydpi: -1
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 3
      depth_max: 10.0
      depth_quantization: 100.0
      enable_pub_plugins:
        - image_transport/compressedDepth
        - image_transport/compressed
        - image_transport/raw
        - image_transport/theora
        - image_transport/zstd
      format: png
      jpeg_quality: 95
      keyframe_frequency: 64
      optimize_for: true
      png_level: 3
      quality: 31
      target_bitrate: 800000
      theora:
        keyframe_frequency: 64
        optimize_for: true
        quality: 31
        target_bitrate: 800000
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
      zstd:
        zstd_level: 3
    image_size:
      - 640
      - 512
    output_encoding: mono16
    pixel_format: "Y16 "
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    start_type_description_service: true
    use_sim_time: false
    video_device: /dev/video4
